"""nullable=True

Revision ID: 42721cacb428
Revises: abc0d40ab3ad
Create Date: 2023-11-13 19:17:46.240765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42721cacb428'
down_revision: Union[str, None] = 'abc0d40ab3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'file_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('images', 'public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('images_file_url_key', 'images', type_='unique')
    op.drop_constraint('images_public_id_key', 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('images_public_id_key', 'images', ['public_id'])
    op.create_unique_constraint('images_file_url_key', 'images', ['file_url'])
    op.alter_column('images', 'public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('images', 'file_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
