"""add qr

Revision ID: 55c10b0ac1ac
Revises: cc1ccaf2d423
Create Date: 2023-11-15 14:05:22.072523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c10b0ac1ac'
down_revision: Union[str, None] = 'cc1ccaf2d423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('qr_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'qr_codes', ['qr_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'qr_code_id')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
