"""add roles for user

Revision ID: 6979199a32ce
Revises: bffda805be8f
Create Date: 2023-11-15 12:01:05.648714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6979199a32ce'
down_revision: Union[str, None] = 'bffda805be8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'),
                                     nullable=True))
    op.execute("UPDATE users SET role='admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute("DROP TYPE role ")
    # ### end Alembic commands ###
