"""file_url

Revision ID: abc0d40ab3ad
Revises: 4d650e93d385
Create Date: 2023-11-13 17:52:55.635447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc0d40ab3ad'
down_revision: Union[str, None] = '4d650e93d385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_url', sa.String(length=250), nullable=False))
    op.drop_constraint('images_fileurl_key', 'images', type_='unique')
    op.create_unique_constraint(None, 'images', ['file_url'])
    op.drop_column('images', 'fileurl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('fileurl', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='unique')
    op.create_unique_constraint('images_fileurl_key', 'images', ['fileurl'])
    op.drop_column('images', 'file_url')
    # ### end Alembic commands ###
